### ISSUE TITLE
Replay attack on withdraw() - possibility of stealing tokens

### ISSUE THREAD

**Issue by gundas** [mysteriumnetwork/payments#21]
Hello,
I am very new to this codebase, so I could be easily mistaken, but I believe that the ```withdraw(...)``` function in ```IdentityBalances.sol``` is vulnerable to a replay attack. And this vulnerability allows stealing other people's tokens.

**Pre-conditions:**
* A user tops-up his balance
*  The same legitimate user calls ```withdraw(...)``` with some valid signature parameters.

**The attack:**
A malicious user can now call the ```withdraw(...)``` with the same ```amount```, ``` v```, ```r``` and ```s``` parameters (since they are publicly visible on the block-chain) and transfer the remaining tokens  to himself.
The malicious user could call the ```withdraw(...)``` function multiple times, as long as the ```amount``` is  still less than the remaining ```balances[identity]```.
The malicious user could call the ```withdraw(...)``` function  again any time later if the balance is topped-up.

**Proposed fix:**
Introduce an uint256 nonce for each identity:
```
mapping(address => uint256) public nonces;
```
Make the nonce part of the signed hash:
```
function withdraw(uint256 amount, uint256 nonce, uint8 v, bytes32 r, bytes32 s) public returns (bool) {
      bytes memory p = abi.encodePacked(WITHDRAW_PREFIX, amount, nonce);
```
Validate that the identity's nonce has not already been used:
```
  require(nonce > nonces[identity]);
```

Update the nonce to the latest value:
``` 
nonces[identity]  = nonce
```

**Important** - the above does not help if the ```withdraw(...)``` functions is called with a valid signature, but it reverts due to an insufficient balance. The valid signature would be still publicly visible, but the ```nonces[identity]``` would not be updated. Once the balance is topped-up, this failed transaction could be replayed (until the legitimate user does a new ```withdraw(...)``` transaction, which would update the nonce). There could be a few possible fixes:
* also increment ```nonces[identity]``` on every balance modification (in both, ```topUp(...)``` and ```internalTransfer()``` functions). This fix introduces some headaches in the future, since any newly added   code which would increase the balance of an identity, should also increment the nonce. Maybe it would be better to encapsulate identity balance increase and nonce modification in a single internal function.

* Add an external function to invalide the nonce. Rely on external off-chain code to always call this function in case the ```withdraw(...)``` fails.

* Change the code to never revert the ```withdraw(...)``` transaction but update the nonce and return ```false``` if anything goes wrong.

**Comment by tadovas** [comment]
@gundas thanks for detailed issue description. Another possible solution to this issue (it has it's own drawbacks), would be - instead of using msg.sender, pass withdrawal address as a parameter (instead of nonce) - ofcourse signed. That way even on replay attack - only owner will get all the withdrawal funds. However this still introduces replay problem - only with much smaller impact. It would be possible for attacker to do some kind of DOSing - once owner issues valid withdrawal and later wants to increase balance, attacker could constantly replay withdraw and send funds back.

**Comment by gundas** [comment]
@tadovas - 
I think  there is another simple solution which might solve all of the problems - if  the signer knows  who will be the ```msg.sender```, then ```msg.sender``` could become a part of a signed message? 
```
bytes memory p = abi.encodePacked(WITHDRAW_PREFIX, amount, msg.sender);
```

This would make replay attacks impossible.

**Comment by tadovas** [comment]
@gundas I was thinking instead of nonce to use blocknumber + some delta, but this sounds brilliant. Thanks for clear description and awesome solution.

**Comment by chompomonim** [comment]
I'm, totally for nonce. It's simple 

The problem is that signer not always knows who will be `msg.sender`. There are situations when people don't have ethers on their account and could potentially use (their wallets would use) 3rd parties to do transactions in their name.

There are already couple of proposals in ethereum community how to make token transfers without using ethers.

**Comment by chompomonim** [comment]
This issue was solved in v2 version of our payment solution.

See smart contracts and protocol's white paper here:
https://github.com/mysteriumnetwork/payments-smart-contracts
